export const ADDRESS_SAVE_REQUEST = 'ADDRESS_SAVE_REQUEST'
export const ADDRESS_SAVE_SUCCESS = 'ADDRESS_SAVE_SUCCESS'
export const ADDRESS_SAVE_FAIL = 'ADDRESS_SAVE_FAIL'
export const CLEAR_SHIPPINGADDRESS_INPUT = 'CLEAR_SHIPPINGADDRESS_INPUT'
